# config/application.yml
defaults: &defaults
  domain: "localhost:3000"
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  facebook:
    key: "6194336540"
    secret: "78bd1186d89dbf1403f3ff129d2f5f8a"

development:
  <<: *defaults
  neat_setting: 800
>>>>>>> social_stream

test:
  <<: *defaults

production:
  <<: *defaults
  domain: "www.styledujour.com"
  facebook:
    key: "2355533850"
    secret: "818a52855bed95cb433ab97435a2212f"

