# config/application.yml
defaults: &defaults
  facebook:
    key: "6194336540"
    secret: "78bd1186d89dbf1403f3ff129d2f5f8a"

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
  facebook:
    key: "2355533850"
    secret: "818a52855bed95cb433ab97435a2212f"